files:
  - source: /**/i18n/en.json
    translation: /**/i18n/%two_letters_code%.json
  - source: /**/**/i18n/en.json
    translation: /**/**/i18n/%two_letters_code%.json
  - source: /fuse-configs/navigation-i18n/en.json
    translation: /fuse-configs/navigation-i18n/%two_letters_code%.json
